package jet

import (
	"context"
	"fmt"

	"github.com/go-jet/jet/v2/postgres"
	"github.com/go-jet/jet/v2/qrm"
)

// Example usage of Jet SQL integration

// ExampleUserTable represents a users table in Jet SQL
// This would typically be generated by Jet SQL code generator
type ExampleUserTable struct {
	postgres.Table
	ID        postgres.ColumnInteger
	Email     postgres.ColumnString
	Username  postgres.ColumnString
	Age       postgres.ColumnInteger
	Status    postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
}

// ExampleJetUsage demonstrates Jet SQL usage
// Note: This is a conceptual example. In practice, use generated tables from Jet SQL generator
func ExampleJetUsage(ctx context.Context, db qrm.DB, userTable *ExampleUserTable) {
	// Basic SELECT query
	// For generated tables, use: table.Users.AllColumns
	stmt := postgres.SELECT(
		userTable.ID,
		userTable.Email,
		userTable.Username,
		userTable.Age,
		userTable.Status,
		userTable.CreatedAt,
	).
		FROM(userTable).
		WHERE(userTable.Status.EQ(postgres.String("active"))).
		ORDER_BY(userTable.CreatedAt.DESC()).
		LIMIT(10)

	var users []struct {
		ID        int64
		Email     string
		Username  string
		Age       int
		Status    string
		CreatedAt string
	}

	err := stmt.QueryContext(ctx, db, &users)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}

	fmt.Printf("Found %d active users\n", len(users))

	// Complex query with JOIN
	// Assuming we have a profiles table
	// profileTable := &ExampleProfileTable{...}
	// stmt = postgres.SELECT(
	// 	userTable.Email,
	// 	userTable.Username,
	// 	profileTable.Bio,
	// ).FROM(userTable.
	// 	INNER_JOIN(profileTable, userTable.ID.EQ(profileTable.UserID)),
	// ).WHERE(userTable.Status.EQ(postgres.String("active")))

	// INSERT query
	// Note: Use Jet SQL INSERT with generated tables
	// insertStmt := postgres.INSERT(userTable).
	// 	COLUMNS(userTable.Email, userTable.Username, userTable.Age, userTable.Status).
	// 	VALUES("newuser@example.com", "newuser", 25, "active")

	// UPDATE query
	// Note: Use Jet SQL UPDATE with generated tables
	// updateStmt := postgres.UPDATE(userTable).
	// 	SET(userTable.Status.SET(postgres.String("inactive"))).
	// 	WHERE(userTable.ID.EQ(postgres.Int64(1)))

	// DELETE query
	// Note: Use Jet SQL DELETE with generated tables
	// deleteStmt := postgres.DELETE(userTable).
	// 	WHERE(userTable.ID.EQ(postgres.Int64(1)))

	// Aggregation query
	aggStmt := postgres.SELECT(
		userTable.Status,
		postgres.COUNT(postgres.Int(1)).AS("count"),
		postgres.AVG(userTable.Age).AS("avg_age"),
	).FROM(userTable).
		GROUP_BY(userTable.Status)

	var stats []struct {
		Status string
		Count  int64
		AvgAge float64
	}

	err = aggStmt.QueryContext(ctx, db, &stats)
	if err != nil {
		fmt.Printf("Aggregation error: %v\n", err)
		return
	}

	for _, stat := range stats {
		fmt.Printf("Status: %s, Count: %d, Avg Age: %.2f\n", stat.Status, stat.Count, stat.AvgAge)
	}
}

// ExampleJetWithHelpers demonstrates using Jet helpers
func ExampleJetWithHelpers(ctx context.Context, db qrm.DB, userTable *ExampleUserTable) {
	// Using helper functions
	qb := NewQueryBuilder(userTable)

	// Build query with helpers
	stmt := qb.SelectAll().
		WHERE(And(
			Equal(userTable.Status, "active"),
			GreaterThan(userTable.Age, 18),
		)).
		ORDER_BY(OrderBy(userTable.CreatedAt, false)).
		LIMIT(Limit(10))

	var users []struct {
		ID       int64
		Email    string
		Username string
		Age      int
		Status   string
	}

	err := stmt.QueryContext(ctx, db, &users)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}

	fmt.Printf("Found %d users\n", len(users))
}

// ExampleJetSubquery demonstrates subqueries
func ExampleJetSubquery(ctx context.Context, db qrm.DB, userTable *ExampleUserTable) {
	// Subquery example
	subquery := postgres.SELECT(userTable.ID).
		FROM(userTable).
		WHERE(userTable.Status.EQ(postgres.String("active")))

	// Use subquery in main query
	stmt := postgres.SELECT(
		userTable.ID,
		userTable.Email,
		userTable.Username,
	).
		FROM(userTable).
		WHERE(userTable.ID.IN(subquery))

	var users []struct {
		ID       int64
		Email    string
		Username string
	}

	err := stmt.QueryContext(ctx, db, &users)
	if err != nil {
		fmt.Printf("Subquery error: %v\n", err)
		return
	}

	fmt.Printf("Found %d users from subquery\n", len(users))
}

// ExampleJetCTE demonstrates Common Table Expressions
func ExampleJetCTE(ctx context.Context, db qrm.DB, userTable *ExampleUserTable) {
	// CTE example
	activeUsersCTE := postgres.SELECT(
		userTable.ID,
		userTable.Email,
		userTable.Username,
		userTable.Age,
	).
		FROM(userTable).
		WHERE(userTable.Status.EQ(postgres.String("active"))).
		AsTable("active_users")

	// Use CTE in main query
	// Note: CTE columns need to be accessed properly
	stmt := postgres.SELECT(activeUsersCTE).
		FROM(activeUsersCTE).
		WHERE(activeUsersCTE.Age.GT(postgres.Int(25)))

	var users []struct {
		ID       int64
		Email    string
		Username string
		Age      int
	}

	err := stmt.QueryContext(ctx, db, &users)
	if err != nil {
		fmt.Printf("CTE error: %v\n", err)
		return
	}

	fmt.Printf("Found %d users from CTE\n", len(users))
}

