package main

import (
	"context"
	"fmt"
	"log"

	"github.com/go-jet/jet/v2/postgres"
	"github.com/go-jet/jet/v2/qrm"
	"github.com/satishbabariya/jetorm/core"
	"github.com/satishbabariya/jetorm/jet"
)

// Example demonstrating Jet SQL integration with JetORM

// User entity
type User struct {
	ID        int64  `db:"id" jet:"primary_key"`
	Email     string `db:"email"`
	Username  string `db:"username"`
	Age       int    `db:"age"`
	Status    string `db:"status"`
}

// ExampleUserTable represents the users table in Jet SQL
// In production, this would be generated by Jet SQL code generator
type ExampleUserTable struct {
	postgres.Table
	ID       postgres.ColumnInteger
	Email    postgres.ColumnString
	Username postgres.ColumnString
	Age      postgres.ColumnInteger
	Status   postgres.ColumnString
}

func exampleJetIntegration() {
	fmt.Println("Jet SQL Integration Example")
	fmt.Println("===========================")

	// Setup (would connect to database in real scenario)
	// db := core.Connect(config)
	// userRepo := core.NewBaseRepository[User, int64](db)

	// Create Jet table (in production, this would be generated)
	// userTable := &ExampleUserTable{
	// 	Table: postgres.Table{Name: "users"},
	// 	ID:    postgres.NewIntegerColumn("id"),
	// 	Email: postgres.NewStringColumn("email"),
	// 	// ... other columns
	// }

	// Create Jet repository adapter
	// jetRepo := jet.NewRepositoryAdapter(userRepo, db, userTable)

	// Example 1: Basic SELECT with Jet SQL
	exampleBasicSelect()

	// Example 2: Complex query with JOIN
	exampleComplexQuery()

	// Example 3: Using Jet helpers
	exampleJetHelpers()

	// Example 4: Combining Jet SQL with JetORM
	exampleCombinedUsage()
}

func exampleBasicSelect() {
	fmt.Println("\n1. Basic SELECT Query")
	fmt.Println("---------------------")

	// In real usage:
	// stmt := postgres.SELECT(userTable.AllColumns()).
	// 	FROM(userTable).
	// 	WHERE(userTable.Status.EQ(postgres.String("active"))).
	// 	ORDER_BY(userTable.CreatedAt.DESC()).
	// 	LIMIT(10)

	// users, err := jetRepo.FindWithJet(ctx, stmt)
	fmt.Println("SELECT * FROM users WHERE status = 'active' ORDER BY created_at DESC LIMIT 10")
}

func exampleComplexQuery() {
	fmt.Println("\n2. Complex Query with JOIN")
	fmt.Println("-------------------------")

	// In real usage:
	// stmt := postgres.SELECT(
	// 	userTable.Email,
	// 	userTable.Username,
	// 	profileTable.Bio,
	// ).FROM(userTable.
	// 	INNER_JOIN(profileTable, userTable.ID.EQ(profileTable.UserID)),
	// ).WHERE(userTable.Status.EQ(postgres.String("active")))

	fmt.Println("SELECT u.email, u.username, p.bio FROM users u")
	fmt.Println("INNER JOIN profiles p ON u.id = p.user_id")
	fmt.Println("WHERE u.status = 'active'")
}

func exampleJetHelpers() {
	fmt.Println("\n3. Using Jet Helpers")
	fmt.Println("---------------------")

	// In real usage:
	// qb := jet.NewQueryBuilder(userTable)
	// stmt := qb.SelectAll().
	// 	WHERE(jet.And(
	// 		jet.Equal(userTable.Status, "active"),
	// 		jet.GreaterThan(userTable.Age, 18),
	// 	))

	fmt.Println("Using helper functions for query building")
	fmt.Println("- jet.Equal()")
	fmt.Println("- jet.GreaterThan()")
	fmt.Println("- jet.And()")
	fmt.Println("- jet.Or()")
}

func exampleCombinedUsage() {
	fmt.Println("\n4. Combining Jet SQL with JetORM")
	fmt.Println("---------------------------------")

	// In real usage:
	// // Use JetORM for simple CRUD
	// user, err := userRepo.Save(ctx, &User{...})
	//
	// // Use Jet SQL for complex queries
	// stmt := postgres.SELECT(userTable.AllColumns()).
	// 	FROM(userTable).
	// 	WHERE(userTable.Age.GT(postgres.Int(25)))
	// users, err := jetRepo.FindWithJet(ctx, stmt)

	fmt.Println("Use JetORM for simple CRUD operations")
	fmt.Println("Use Jet SQL for complex queries")
	fmt.Println("Best of both worlds!")
}

func exampleAdvancedJetFeatures() {
	fmt.Println("\n5. Advanced Jet SQL Features")
	fmt.Println("----------------------------")

	// CTE example
	fmt.Println("CTE (Common Table Expressions):")
	fmt.Println("WITH active_users AS (SELECT * FROM users WHERE status = 'active')")
	fmt.Println("SELECT * FROM active_users WHERE age > 25")

	// Subquery example
	fmt.Println("\nSubquery:")
	fmt.Println("SELECT * FROM users WHERE id IN (SELECT user_id FROM orders)")

	// Window functions
	fmt.Println("\nWindow Functions:")
	fmt.Println("SELECT email, age, ROW_NUMBER() OVER (PARTITION BY status ORDER BY age DESC) FROM users")

	// Aggregations
	fmt.Println("\nAggregations:")
	fmt.Println("SELECT status, COUNT(*), AVG(age) FROM users GROUP BY status")
}

func main() {
	exampleJetIntegration()
	exampleAdvancedJetFeatures()
}

